# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               rgb
tagline:             "ruba's graphics blog"
description:         "I'm learning graphics programming and writing about it"
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ruba Merza
  url:               https://twitter.com/rubamoh
  email:             me@ruba.io

# Custom vars
version:             1.0.0
